apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - backendconfig.yaml

images:
  - name: catalog-service
    newName: us-central1-docker.pkg.dev/srini-schwab-demo-062020026/apps/catalog-service
    newTag: "202606202054"
